version: '3'

services:
  db:
    container_name: docker-local-mysql
    image: mysql:8.0.14
    volumes:
      - "./data:/docker-entrypoint-initdb.d"
    restart: always
    ports:
      - 8080:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
